language: node_js
dist: focal
node_js:
  - 14
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgmp-dev nlohmann-json3-dev nasm g++ build-essential libsodium-dev git

install:
  - npm i -g npm
  - npm i
  - npm run bootstrap
  - npm run build
  - cd circuits
  - wget http://launchpadlibrarian.net/531361873/libc6_2.33-0ubuntu5_amd64.deb
  - sudo dpkg --auto-deconfigure -i libc6_2.33-0ubuntu5_amd64.deb
  - ./scripts/downloadTestCircuits.sh
  - npm run build-test-circuits
  - ./scripts/installRapidsnark.sh

script:
  - cd ../crypto && npm run test
  - cd ../domainobjs && npm run test
  - cd ../core && npm run test
  - cd ../circuits && ./scripts/runTestsInCi.sh
  - cd ../contracts && ./scripts/compileSol.sh 
  - ./scripts/runTestsInCi.sh
  - cd ../integrationTests && ./scripts/runTestsInCi.sh
