version: '3'
services:
  maci-node:
    tty: true
    image: maci-node:a3
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      mongo_host: mongo
      mongo_user: maci-coordinator
      mongo_pass: let-me-in
      mongo_db: maci-db
      mongo_uri: 'mongodb://maci-coordinator:let-me-in@host.docker.internal'
      hardhat_uri: 'http://host.docker.internal:8545'
    volumes:
      - /home/chao/opensource/maci:/root/dev-maci
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: maci-coordinator
      MONGO_INITDB_ROOT_PASSWORD: let-me-in
    volumes:
      - ./data/mongodb:/data/db
