---
env: 'prod-large'

maci:
  initialVoiceCreditBalance: 100
  signUpDurationInSeconds: 3600 # 1 hour
  votingDurationInSeconds: 3600 # 1 hour
  coordinatorPrivKey: "2222222222263902553431241761119057960280734584214105336279476766401963593688"
  messageBatchSize: 4
  quadVoteTallyBatchSize: 4
  voteOptionsMaxLeafIndex: 3

  merkleTrees:
    stateTreeDepth: 10
    messageTreeDepth: 17
    voteOptionTreeDepth: 5

chain:
  privateKeysPath: '/home/di/MACI_PRIVATE_KEYS'
  testMnemonic: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
  url: "http://localhost:8545"
  ganache:
    port: 8545

zkutil_bin: "~/.cargo/bin/zkutil"
