---
env: 'test'

maci:
  initialVoiceCreditBalance: 100
  signupDurationInSeconds: 3600 # 1 hour
  coordinatorPublicKey:
    - 0
    - 1

chain:
  privateKeysPath: './'
  testMnemonic: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
  url: "http://localhost:8545"
  ganache:
    port: 8545

merkleTrees:
  commandTreeDepth: 4
  stateTreeDepth: 4
  voteOptionTreeDepth: 4
