---
env: 'test'

maci:
  initialVoiceCreditBalance: 100
  signupDurationInSeconds: 3600 # 1 hour
  coordinatorPrivKey: "2922056879163902553431241761119057960280734584214105336279476766401963593688"
  messageBatchSize: 4
  stateLeafBatchSize: 4
  voteOptionsMaxLeafIndex: 3

  merkleTrees:
    stateTreeDepth: 4
    messageTreeDepth: 4
    voteOptionTreeDepth: 4

chain:
  privateKeysPath: './'
  testMnemonic: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
  url: "http://localhost:8545"
  ganache:
    port: 8545
